name: Cypress Tests using Cypress Docker Image

on: push

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Cypress install
        uses: cypress-io/github-action@v6.5.0
        with:
          runTests: false
      # report machine parameters
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
      options: --user 1001
    needs: install
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving Cypress Cloud hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3,]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node info
        run: node -v
        
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v6.5.0
        with:
          build: yarn cypress info
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/e2e/cucumber-tests/featureFiles/*
          config-file: cypress.config.ts
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "cypress:server:args"
